---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r library}
library(tidyverse)
library("rprime")
```

```{r}
lf<-list.files("DATA", pattern = "txt")
for(i in 1:length(lf)){
# Read in a text file generated by Eprime
lfi <- lf[i]
wm_lines <- read_eprime(paste0("DATA/", lfi))
# Convert lines from an Eprime file into EprimeFrame objects
wm_frames <- FrameList(wm_lines)
# Make it a data frame.
df <- to_data_frame(wm_frames)
# View(df)

dfvv<-df %>% 
  filter(Procedure == "blocVVstim") %>% 
  select(offset, vvstimresp1.CRESP, vvstimresp1.RESP,
         vvstimresp1.ACC) %>% 
  mutate(deg = as.numeric(offset)/10,
         resp_dummy = ifelse(vvstimresp1.RESP == "1",
                             0, 1))
# table(dfvv$offset)
# str(dfvv)
model<-glm(resp_dummy ~ deg, family = binomial(link = "logit"), dfvv) 
coeff<-as.data.frame(t(summary(model)$coefficients))[1,]
colnames(coeff)<-c("intercept", "deg")
pse <- -coeff$intercept/coeff$deg
slope <- coeff$deg
jnd <- log(3/slope)

plot<-ggplot(dfvv, aes(x = deg, y = resp_dummy))+
  geom_hline(yintercept = 0.50, lty = "dashed", col = "grey", size=0.7)+
  geom_vline(xintercept = unlist(pse), lty = "dashed", col = "grey", size=0.7)+
  # scale_x_continuous(limits=c(-2,2),breaks = seq(-2,2,0.5))+
  geom_smooth(method = "glm", method.args = list(family = "binomial"),se = F, size=1)+
  geom_jitter(size = 1, alpha = 0.5, width = 0.02,height=0.06, 
              col = "black",fill="red",
              stroke = 1, shape = 21)+
  geom_point(aes(x=unlist(pse), y=0.5), fill="red", size=3, col = "black", shape=24,
             stroke = 1.2)+
  scale_y_continuous(limits=c(-0.1,1.1),breaks = seq(0,1,0.5),
                     labels = c("0%\nreponse gauche",
                                paste0("50%\nvotre verticale\nsubjective est\ndecalee de\n",
                                       round(pse,1), "°"), 
                                       "100%\nreponse droite"))+
  labs(y="% de reponse 'ligne orientee a droite'", x= "Decalage de la ligne \npar rapport a la verticale (deg)",
       title = lfi)+
  theme_bw(base_size = 10)
print(plot)
ggsave(paste0("PLOT/VV", lfi, ".pdf"), plot)

print(lfi)
print("SA")
df %>% 
  filter(Procedure == "TrialSA") %>% 
  select(TrialSA, Mouse.X) %>% 
  unique() %>% 
  mutate(sa = as.numeric(Mouse.X) - 1280) %>% 
  mutate(samm = (60*sa)/2560) %>% 
  summarise(bias_sa = mean(samm)) %>% 
  print(.)
}
```

